version: "3.9"

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"

  playwright:
    image: mcr.microsoft.com/playwright:v1.49.0-jammy
    depends_on:
      - app
    working_dir: /tests
    volumes:
      - ./:/tests
    environment:
      BASE_URL: "http://app:8000"
    command: >
      npx playwright test
